# Generated by Django 6.0.1 on 2026-01-23 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publication_data',
            new_name='publication_date',
        ),
    ]
