# Generated by Django 6.0.1 on 2026-01-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='article-slug', max_length=200),
            preserve_default=False,
        ),
    ]
