# Generated by Django 6.0.1 on 2026-01-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='snippet',
            field=models.CharField(default='snippet', max_length=280),
            preserve_default=False,
        ),
    ]
