# Generated by Django 6.0.1 on 2026-01-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_article_cover_image_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.CharField(choices=[('nf', 'Nonfiction'), ('f', 'Fiction'), ('p', 'Poetry')], default='f'),
            preserve_default=False,
        ),
    ]
