# Generated by Django 6.0.1 on 2026-01-25 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_article_cover_image_credit'),
        ('images', '0004_alter_image_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='cover_image_credit',
        ),
        migrations.AddField(
            model_name='article',
            name='a_cover_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='images.image'),
        ),
    ]
