# Generated by Django 6.0.1 on 2026-01-25 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_rename_a_cover_image_article_cover_image'),
        ('images', '0004_alter_image_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='images.image'),
        ),
    ]
