# Generated by Django 6.0.1 on 2026-01-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_alter_article_cover_image'),
        ('images', '0004_alter_image_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_images',
            field=models.ManyToManyField(blank=True, related_name='articles', to='images.image'),
        ),
    ]
