# Generated by Django 6.0.1 on 2026-03-13 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_article_content_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author_email',
        ),
    ]
