# Generated by Django 6.0.1 on 2026-01-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='keywords',
            field=models.CharField(default='image, text', max_length=280),
            preserve_default=False,
        ),
    ]
