# Generated by Django 6.0.1 on 2026-01-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_image_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='author',
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
