# Generated by Django 6.0.1 on 2026-01-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('caption', models.TextField(blank=True)),
                ('slug', models.CharField(max_length=280)),
                ('author', models.CharField(max_length=280)),
                ('author_url', models.URLField(blank=True)),
                ('author_email', models.EmailField(blank=True, max_length=254)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('publication_date', models.DateField(blank=True)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-upload_date', '-slug'],
            },
        ),
    ]
