# Generated by Django 6.0.1 on 2026-01-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
