# Generated by Django 6.0.1 on 2026-03-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_alter_image_author_alter_image_author_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='author_email',
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='Untitled', max_length=280),
        ),
    ]
