# Generated by Django 6.0.1 on 2026-03-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_remove_image_author_email_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.CharField(max_length=280, unique=True),
        ),
    ]
