# Generated by Django 6.0.1 on 2026-03-17 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_alter_image_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
