# Generated by Django 4.2.27 on 2026-01-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('author_url', models.URLField(blank=True)),
                ('author_email', models.URLField(blank=True)),
                ('cover_image', models.ImageField(upload_to='images/')),
                ('cover_image_credit', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('publication_data', models.DateField()),
                ('published', models.BooleanField(default=False)),
                ('keywords', models.CharField(max_length=200)),
            ],
        ),
    ]
