# Generated by Django 6.0.1 on 2026-01-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_publication_data_article_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
