# Generated by Django 6.0.1 on 2026-01-24 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publication_date']},
        ),
    ]
