# Generated by Django 6.0.1 on 2026-01-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_image_credit',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(editable=False, max_length=280),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=280),
        ),
    ]
