# Generated by Django 6.0.1 on 2026-01-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image_credit',
            field=models.TextField(max_length=280),
        ),
        migrations.AlterField(
            model_name='article',
            name='snippet',
            field=models.TextField(max_length=280),
        ),
    ]
