# Generated by Django 6.0.1 on 2026-01-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_image_credit',
            field=models.TextField(blank=True, max_length=280),
        ),
        migrations.AlterField(
            model_name='article',
            name='snippet',
            field=models.TextField(),
        ),
    ]
