# Generated by Django 6.0.1 on 2026-01-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image_credit',
            field=models.TextField(blank=True),
        ),
    ]
