# Generated by Django 6.0.1 on 2026-01-25 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_remove_article_cover_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='a_cover_image',
            new_name='cover_image',
        ),
    ]
