# Generated by Django 6.0.1 on 2026-03-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DawnArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('nf', 'Nonfiction'), ('f', 'Fiction'), ('p', 'Poetry'), ('i', 'Image')])),
                ('title', models.CharField(max_length=280)),
                ('slug', models.SlugField(editable=False, max_length=280)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.CharField(max_length=280)),
                ('author_name', models.CharField(max_length=280)),
                ('author_url', models.URLField(blank=True)),
                ('publication_date', models.DateField()),
                ('published', models.BooleanField(default=False)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['-publication_date'],
                'abstract': False,
            },
        ),
    ]
