# Generated by Django 6.0.1 on 2026-03-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_dawnimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(blank=True)),
                ('upload_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-upload_datetime'],
            },
        ),
    ]
