# Generated by Django 6.0.1 on 2026-03-17 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-modified_datetime']},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='upload_datetime',
            new_name='modified_datetime',
        ),
    ]
