# Generated by Django 6.0.1 on 2026-03-17 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dawnarticle',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.image'),
        ),
    ]
