# Generated by Django 6.0.1 on 2026-03-17 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_dawnarticle_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dawnimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.image'),
        ),
    ]
