# Generated by Django 6.0.1 on 2026-03-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_alter_dawnimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dawnarticle',
            name='content_images',
            field=models.ManyToManyField(blank=True, related_name='dawn_articles', to='objects.image'),
        ),
    ]
