# Generated by Django 6.0.1 on 2026-03-17 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyper', '0002_image_fragment_fragments_fragment_content_images'),
        ('objects', '0007_dawnarticle_content_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dawnarticle',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hyper.image'),
        ),
        migrations.AlterField(
            model_name='dawnimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyper.image'),
        ),
        migrations.AddField(
            model_name='dawnarticle',
            name='fragments',
            field=models.ManyToManyField(blank=True, related_name='dawn_articles', to='hyper.fragment'),
        ),
        migrations.AlterField(
            model_name='dawnarticle',
            name='content_images',
            field=models.ManyToManyField(blank=True, related_name='dawn_articles', to='hyper.image'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
