# Generated by Django 6.0.1 on 2026-03-17 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0008_alter_dawnarticle_cover_image_alter_dawnimage_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dawnarticle',
            old_name='content_images',
            new_name='images',
        ),
    ]
