# Generated by Django 6.0.1 on 2026-03-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-modified_datetime'],
            },
        ),
    ]
