# Generated by Django 6.0.1 on 2026-03-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(blank=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-modified_datetime'],
            },
        ),
        migrations.AddField(
            model_name='fragment',
            name='fragments',
            field=models.ManyToManyField(blank=True, related_name='parent_fragments', to='hyper.fragment'),
        ),
        migrations.AddField(
            model_name='fragment',
            name='content_images',
            field=models.ManyToManyField(blank=True, related_name='fragments', to='hyper.image'),
        ),
    ]
