# Generated by Django 6.0.1 on 2026-03-17 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyper', '0002_image_fragment_fragments_fragment_content_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fragment',
            old_name='content_images',
            new_name='images',
        ),
    ]
