# Generated by Django 6.0.1 on 2026-03-21 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyper', '0003_rename_content_images_fragment_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fragment',
            name='slug',
        ),
    ]
